### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by ohenley** [morbos/STM32#1]
Hi Hedley,

I want to add your work for the sensortile, and any meaningful (community wise) work of yours really, to the awesome-ada list. https://github.com/ohenley/awesome-ada/edit/master/README.md

I have comments though because things are, IMHO, misleading a bit. Here:

1. The hub page - where the sensortile context/annoncement is done - is directly on http://www.hrrzi.com/. In the long run, I cannot point to that url, because new 'work news' will be pushed over, I suppose. IMO, sensortile high overview informations would need a dedicated url. 
Then enters the tremendous github convenience with specific repos, readmes etc.

2. If we check on the github side of things, the entry point for sensortile is https://github.com/morbos/STM32/. 
    - the readme.md is completly out of sync, and the general name stm32 is quite generic.
    - if we move to the proper url /L/L476/sensortile. We find no readme.md. This is not ideal for someone new to your work, embedded stuff, and or Ada in general.

There is many solutions for that:
- update infos at root of STM32 and create a readme.md at /L/L476/sensortile
- create another github repo named sensortile and add it as a submodule to stm32 repo.
- make a http://www.hrrzi.com/sensortile dedicated page or something similar, anchor on the index.hml maybe.
- anything else that works for you but stays stable and gives proper context for a newcomer.

Personnally, I think the readme.md are the way to go, much easier to produce than full fledge html, you can link all kind of things even videos. If you need example for some 'advanced' mardown syntax to add eg. videos thumbnails and url to your readme, please edit and check the code inside https://github.com/ohenley/readme-template/blob/master/README.md. Common tricks are laid out as examples for convenience. Also the general format is good to follow as a template that pertinent and complete overview for a project to newcomers.

Give me news please. Ill wait for a solution of yours before adding the project to the list because really, the work is amazing but it is way to 'brutal' as-is.

Thank you,

Olivier

**Comment by morbos** [comment]
Thanks Olivier for the kind suggestions. I am not good at web documentation. If you see my proj doc for this its in TeX! :) (I am old).

I will go with the readme.md format you suggest. Seems an interesting meta format. I looked at your readme.md as a raw file, saved it and will be making a suitable one for the sensortile.

STM32 was to cover all my hacking across all parts. Thats why there are L and F subdirs. I do a bit of work in F/F103 and L/L443, soon there will be a WB dir also in march.

Best,

Hedley

**Comment by ohenley** [comment]
Good!

I really like TeX, well ... I know LaTex back from school and anytime I do a serious report I use it.

So you see, thats the thing I want to know as a newcomer, why L, F, WB. Maybe also some links to the the different L443, link your video. You know, try to be in the shoes of someone coming from eg. python, a junior that just learned from Ada and wants to make a great project using the sensor tile. This person just needs the 'story', key infos that lower the entry barrier. He will find the rest, he just needs to be excited to start coding. Ada strive for its clarity, and needs adopters. So, IMO we need this extra push even though such 'summary exercise' can be tiresome.

Thanks Hedley, nice chatting with you. Give news when you are ready.

Olivier

**Comment by morbos** [comment]
Olivier, I updated the README.md. With those linux instructions, I can build from top of tree. Before this btw from a fresh clone... I could not! Thanks for poking me, my local env was not being reflected over on Github nor were any reasonable instructions in place! Windows... *sigh* despite having the toolchain in place etc, its moaning about something. Hopefully this example Python programmer won't be from a Windows background... for now! :)

**Comment by ohenley** [comment]
ok the readme is great.

Where would you categorize the sensortile on the Awesome-Ada page? Under Hardware and Embedded for sure but where would you think it fits best?

#### Frameworks
#### Firmwares
#### Drivers
#### Controllers
#### Libraries
#### Applications

Thx,

Olivier

p.s: we can add a new category if none are exact.

**Comment by morbos** [comment]
Maybe a new category under embedded hw? Communication? Leaves open a category of these types of devices and attendant fw.

tnx

Hedley

**Comment by ohenley** [comment]
Good with you?

https://github.com/ohenley/awesome-ada/blob/master/README.md#Communication

**Comment by morbos** [comment]
It is...... good!
